[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "mlcg_tk"
version = "0.0.1"
description = "A collection of tools for processing raw simulation data for use in training machine-learned, coarse-grained (CG) force fields using the MLCG library"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.12"
authors = [
  {name = "Andrea Guljas"},
  {name = "Aldo S. Pasos-Trejo"},
  {name = "Klara Bonneau"},
  {name = "Luca Sagresti"},
  {name = "Edoardo Rolando"},
  {name = "Jacopo Venturin"},
  {name = "Felix Musil"},
]
license = "MIT"
license-files = ["LICENSE"]

dependencies = []

classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3.12",
]

[dependency-groups]
dev = [
  "black[jupyter]",
  "coverage[toml]",
  "pytest",
  "pytest-split",
]
docs = [
  "sphinx",
  "shibuya",
  "sphinx-autodoc-typehints",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["mlcg_tk*", "input_generator*"]

[project.urls]
Homepage = "https://github.com/ClementiGroup/mlcg-tk"
Issues = "https://github.com/ClementiGroup/mlcg-tk/issues"

[project.scripts]
mlcg-tk-gen_input_data = "mlcg_tk.scripts.gen_input_data:main"
mlcg-tk-fit_priors = "mlcg_tk.scripts.fit_priors:main"
mlcg-tk-merge_statistics = "mlcg_tk.scripts.merge_statistics:main"
mlcg-tk-package_training_data = "mlcg_tk.scripts.package_training_data:main"
mlcg-tk-produce_delta_forces = "mlcg_tk.scripts.produce_delta_forces:main"
mlcg-tk-add_decoys = "mlcg_tk.scripts.add_decoys:main"
mlcg-tk-gen_sim_input = "mlcg_tk.scripts.gen_sim_input:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "integration: slow CLI / system integration tests",
    "unit: fast unit tests",
]
filterwarnings = [
    "ignore::DeprecationWarning"
]



